### ISSUE TITLE
HttpBridgeTest uses deprecated httpclient post methods

### ISSUE THREAD

**Issue by hifly81** [strimzi/strimzi-kafka-bridge#126]
io.vertx.core.http.HttpClient
provides post methods that are deprectaed (they will break vert.x 4.x)

consider the usage of vertx-web-client instead.

**Comment by ppatierno** [comment]
@hifly81 we are using the HttpClient just for testing and the breaking changes could be easily fixed when the Vert.x 4 will be released. HttpClient seems to be more tailored for HTTP request/response while Web client is more "web" oriented. Let me think more, but I would stick with the current client and then fixing the tests when Vert.x 4 will be here. Wdyt?

**Comment by hifly81** [comment]
@ppatierno I understand your point. It depends on the kind of tests you are preparing.
I dind't find regressions using the web client for testing the HttpBridge class.
Basically the web client inherits the best from http client and adds other features.
However the web client does not provide a WebSocket API, the Vert.x Core HttpClient should be used. It also does not handle cookies at the moment.
But your point is reasonable.
Ciao!
