### ISSUE TITLE
HTTP POST for subscribe doesn't start a rebalance

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi-kafka-bridge#161]
The current way the subscribe work, due to how the native Kafka consumer client works, the partitions are not assigned to the HTTP consumer joining the group.
The current HTTP POST on "/subscription" just does a subscribe call on the Kafka consumer client but it needs a poll for actually allowing the client to join the group and getting partitions assigned.
Currently after an HTTP POST on "/subscription", an HTTP GET on "/records" is needed for joining the group (because a poll is executed) but no records are returned (even if there are some in the topic). Only, on a second HTTP GET on "/records" (so doing a second poll), the records are returned.

**Comment by ppatierno** [comment]
Thinking more there is nothing to fix here, this is exactly how native Kafka client and the Kafka protocol works.
In a Kafka application, after subscribing, the client does a poll loop so the first poll will trigger the rebalance.
I don't think that we should push for "simulate" (actually doing) a first poll on subscribe but we should leave the behavior as it is for a native Kafka client.
The HTTP client will do a subscribe and after that we would expect a poll loop made by HTTP poll requests (and the first one will start the actual rebalancing).
@stanlyDoge @tombentley wdyt?

**Comment by tombentley** [comment]
I agree @ppatierno.
