### ISSUE TITLE
Sink endpoint not removed and Kafka consumer not closed if HTTP client close connection without DELETE

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi-kafka-bridge#187]
If the HTTP client doesn't do a DELETE on the consumer endpoint for closing the Kafka consumer and removing the sink endpoint, it won't be removed anymore in the `closeConnectionEndpoint`.

**Comment by ppatierno** [comment]
Thinking more on this, there is no strict relationship between the HTTP connection and the related "named" sink endpoint. 
An HTTP client can create a consumer and then close the connection. Then open a new connection for doing subscribe, poll and so on. It can do the same every time with a new connection.
So if at some point the HTTP client close the connection that should not be the same as the one when the consumer was created in the sink endpoint.
The only way to clear sink endpoint and Kafka consumer not closed properly due to a missing HTTP DELETE is implementing #101 with a deletion on timeout.
@stanlyDoge @tombentley wdyt?

**Comment by tombentley** [comment]
I agree that the lifetime of the consumer should not be coupled to the lifetime of the HTTP connection.

I agree #101 is part of the solution for ensuring that the bridge doesn't become a source of leaking connections.
