### ISSUE TITLE
Handle error on seek operations if the consumer is not assigned to the partitions

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi-kafka-bridge#195]
What happens if the consumer does a seek operation specifying offsets but for partitions to which it isn't subscribed (or they are not assigned)?
The same for seek to end and beginning.

**Comment by ppatierno** [comment]
@tombentley actually the seek on the native client raises an `IllegalStateException` with message i.e "No current assignment for partition test-0". The bridge in this case catch the exceptions and return a 500 error to the HTTP client with a specific Error JSON encoded body as this one.

```json
{
    "error_code": 500,
    "message": "No current assignment for partition test-0"
}
```

**Comment by tombentley** [comment]
I have no problem with the message. I agree that it's not a server error. If you squint it looks like a 404 to me.

**Comment by ppatierno** [comment]
It can make sense, it could sound like "we cannot find your assignment" :)
