### ISSUE TITLE
Allow consumer and producer configuration within the properties file

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi-kafka-bridge#205]
Instead of having a sort of "hard-coded" parameters and fields for the bridge configuration we should also allow consumer and producer configuration.
The properties file should use `kafka.consumer` and `kafka.producer` prefixes for all consumer and producer related parameters that could be overridden by the specific ones when an HTTP client connect.
The same for specific configuration related to HTTP and AMQP so using prefixes `http` and `amqp`.

**Comment by nkarw** [comment]
I apologize to add a comment to a closed issue. I didn't want to open another one.

I am trying to run this bridge using HTTPS. I have all my certs ready. What entries I need to make in the application.config file in the HTTP section. I was able to connect to a secure Kafka cluster using kafka.producer.ssl and so on. I am a little unsure about how to enable the bridge for HTTPS. I am running this on an EC2 instance.

One basic question. Do I need to run this bridge on a web server (e.g. Nginx) or there is something already embedded in the code?

**Comment by ppatierno** [comment]
The bridge doesn't support TLS so it doesn't support HTTPS.
The way for having that is having an API gateway in front of it or even a reverse proxy providing TLS and then forwarding the traffic to the bridge via HTTP.

**Comment by nkarw** [comment]
Thanks you for the information.
