### ISSUE TITLE
Initial version number

### ISSUE THREAD

**Issue by tombentley** [strimzi/strimzi-kafka-bridge#209]
I'd like to propose that we release the bridge with version 0.12.0 (i.e. that we keep releases of the bridge in sync with releases of the operators). This is based on the assumption that the bridge and the operators would always be released together. 

It seems to me that having one fewer version number to keep track of (and releasing these things together, rather than having separate release schedules) ultimately makes our lives simpler. I know this release of the bridge "ought to" be 0.1.0, and releasing it as 0.12.0 suggests it's a bit more mature than it really is, but to be honest that argument only holds for the initial release. I think a year from now having 0.x.0 or the bridge and 0.y.0 of the operator will feel like a pointless distinction. 

The other assumption here is that both components would move to 1.0.0 at the same time. Since we've not fully discussed what we need to do for the operators to move to 1.0.0 it's difficult to really judge whether it would be reasonable for them both to become 1.0.0 at the same time, or not.

**Comment by ppatierno** [comment]
They will be released together but could live not together. Thinking about people using the bridge for the first time on bare metal and see that its release is 0.12.0.
Anyway, I can live with that; making our life simpler is the most important things.

**Comment by scholzj** [comment]
There is already release 0.11.2. So the new release cannot be 0.1.0. So by coincidence 0.12.0 fits into that line. 

But I'm strongly against this idea:

> that we keep releases of the bridge in sync with releases of the operators

If we want to do this, we should have moved it to the main repo in the first place. The releases should be independent so that we release the bridge only when it is needed.

**Comment by tombentley** [comment]
When did we release a 0.11.2 of the bridge?

> If we want to do this, we should have moved it to the main repo in the first place.

I don't recall that being the sole criterion for the decision. There were other factors too, like the fact that the bridge is useful outside kube and burying it inside the operator repo would make it more difficult for people to find and use it in that context.

> The releases should be independent so that we release the bridge only when it is needed.

We still have that option open to us, of course. But if they're not going to evolve in step then actually starting them off with the same version number will make things _more_ confusing later on.

**Comment by scholzj** [comment]
> When did we release a 0.11.2 of the bridge?

I assume that was when it was still part of EnMasse. But it is in the repo, might be linked etc.

> We still have that option open to us, of course. But if they're not going to evolve in step then actually starting them off with the same version number will make things more confusing later on.

Right. We can make it 0.20.0 to distinguish it a bit more. For me independent release cycle was the main reason why not put it into the same repo. I do not think we will be making changes to the bridge with the same frequency as to the operators. So when you release it together, you will be soon releasing empty releases with no changes. And the release is not for free, it costs some time.

**Comment by tombentley** [comment]
So let's use 0.12.0. If we used 0.20.0 we might end up with the operators overtaking the bridge in the future anyway, so confusion only deferred rather than avoided.
