### ISSUE TITLE
Moving the "healthy" and "ready" endpoints as part of the OpenAPI spec

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi-kafka-bridge#264]
Currently, the bridge starts a "health" server on port 8081 by default (configurable via `HEALTH_SERVER_PORT` env var) replying to HTTP requests on `/healthy` and `/ready` endpoints as for liveness and readiness probes on Kubernetes.
This choice was made because we need such support even for AMQP bridging and not just HTTP.
Thinking more I am proposing to:

* start this "health" server only if only AMQP bridging is enabled so that it can use the default 8080 port
* exposing the "health" endpoints in the OpenAPI spec

In this case, the "healthy" is always tested on a standard HTTP 8080 port.
When only AMQP is running (or any other protocol i.e. MQTT which is not HTTP), the "health" server is in charge to reply liveness and readiness requests.
When HTTP is running, it's in charge to expose these endpoints (even if AMQP is running at the same time).

Nothing changes from users/client/Kubernetes perspective because they can always test `/healthy` and `/ready` endpoints on HTTP port 8080.

Any thoughts @tombentley @stanlyDoge @scholzj @kyguy ?

**Comment by tombentley** [comment]
Seems like a good idea to me.
