### ISSUE TITLE
Consumer base_uri field filled with API gateway host if needed

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi-kafka-bridge#265]
When a new consumer is created, the `base_uri` returned in the HTTP body by the bridge contains the address to be used by the client for subsequent consumer operations.
The bridge uses the HTTP "Host" header for getting the address that the HTTP client has to call.
Using an API gateway (i.e. 3scale) in front of the bridge changes the scenario.
The HTTP client is using the API gateway address and it should be used in the future requests but because the bridge isn't aware that the request comes from an API gateway, just use the "Host" header and .... the client gets the bridge address instead of the API gateway one in the `base_uri` field.

For example, client sends request to:

```
http://gateway.192.168.1.9.nip.io:8080/consumers/my-group
```

but the `base_uri` in the JSON response is: 

```
http://bridge.192.168.1.9.nip.io:8083/consumers/my-group/instances/consumer1
```

On solution could be having the API gateway adding a custom header in each request like `API_GATEWAY_HOST` so that the bridge can use this one instead of the default "Host" as base address in the `base_uri`.

@tombentley @scholzj @kyguy @stanlyDoge any thoughts?

**Comment by tombentley** [comment]
I think the basic idea is sound, but I don't think a custom header should be necessary. This is what the standard [`Forwarded`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Forwarded) header is for (in particular the host part of that), and I would expect 3scale or any other gateway would be setting that header. We would also need to support the `X-Forwarded-Host` header, which is likely also in common usage. We'd also need to use the `proto` to construct a full URI (actually a URL). We should try to avoid relying on custom headers if standard or de-facto standard headers already exist.

**Comment by ppatierno** [comment]
I was thinking about a custom header because the API gateway I am trying to use (3scale) doesn't add these headers by default. Btw it seems provides a way (they call them "policies") to add custom headers so I could try that. I agree that using standard headers is better than custom ones.

**Comment by tombentley** [comment]
Do `X-Forwarded-Host` and `X-Forwarded-Proto` counts as custom headers?

**Comment by ppatierno** [comment]
@tombentley anyway even reading from the mozilla webside about the `X-Forwarded-YYYY` headers there is a warning:

Non-standard. Expect poor cross-browser support

So anyway they are not standard.

**Comment by tombentley** [comment]
This has nothing to do with browsers. These headers would be added by the proxy that sits between a client (which _may_ be a browser) and the bridge. So it's support for these (or at least custom) headers in the proxy that you care about.

**Comment by ppatierno** [comment]
I am just making the point that they are anyway "custom" not "standard" just that. I am fine using those names.

**Comment by ppatierno** [comment]
So using 3scale I was able to use a header policy to add `X-Forwarded-Host` getting the Nginx `$host` variable exposed via Liquid. Currently, there is no way of getting the scheme and the port. I had a call with @eloycoto from 3scale team and he opened an issue for adding more information.

https://github.com/3scale/APIcast/issues/1079

At the end, I will be able to use `X-Forwarded-Host`, `X-Forwarded-Proto` and `X-Forwarded-Port` even if the last one is completely custom because doesn't exist, in the Mozilla documentation neither.
While Eloy works on having them available I can change the bridge accordingly.

**Comment by ppatierno** [comment]
The issue was fixed by the 3scale team now it's possible to create a header policy at 3scale configuration to add the three `X-Forwarded` headers so that the bridge can use them for building the `base_uri` field or if not present continue to use `Host` as today.
