### ISSUE TITLE
Fix consumerOrPartitionNotFound test

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi-kafka-bridge#282]
The `consumerOrPartitionNotFound` test is completely wrong.
Starting from the topic name used (it was a copy/paste error I guess) then for every async call there is no waiting on the related completable future.
The consumer creation is completing a completable future already completed (the `creation` one) which was related to topic creation.
Finally, I am not pretty sure what the test is about :-(
@serrss any idea?
We are really lucky that it's passing!

**Comment by serrss** [comment]
This issue was fixed in the scope of #294
