### ISSUE TITLE
Internal server error during receiving records

### ISSUE THREAD

**Issue by serrss** [strimzi/strimzi-kafka-bridge#297]
Kafka Bridge returns `internal server error` if try to receive records from unsubscribed topic. 

**Steps to reproduce:**
1. Create Kafka Topic
2. Create consumer via Kafka Bridge API using endpoint `POST /consumers​/{groupid}`
3. Receive records using endpoint `GET ​/consumers​/{groupid}​/instances​/{name}​/records`
Actual Result: Response has HTTP code 500 and message `Internal Server Error`
Expected Result: Response should have HTTP code 4xx and message that you need to subscribe or assignment to a topic.

JFYI: If subscribe or assignments to a topic before reading records it's NOT possible to reproduce this issue.

**Comment by ppatierno** [comment]
This error is related to the following Vert.x Kafka client issue:

https://github.com/vert-x3/vertx-kafka-client/issues/131

The NPE is raised and the bridge doesn't have more information for sending a proper error, so the "internal server error" is used.

**Comment by ppatierno** [comment]
Going to close this because right now the client gets `"Consumer is not subscribed to any topics or assigned any partitions"` as message.
