### ISSUE TITLE
Adding operation for getting current subscribed topics

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi-kafka-bridge#298]
On the `/consumers/{groupid}/instances/{name}/subscription` endpoint should be possible to make a GET (HTTP request) in order to get the currently subscribed topics for the consumer.
It's not an administrative API because it's provided by the underlying native Kafka consumer client via the `assignment` method (which provides topics with related partitions).
The GET should Accept `application/vnd.kafka.v2+json` and the bridge should return something like:

```shell
HTTP/1.1 200 OK
Content-Type: application/vnd.kafka.v2+json

{
  "topics": [
    "my-topic1",
    "my-topic2"
  ]
}
```

**Comment by stanlyDoge** [comment]
We started a discussion that response should also contain partitions of topics which is consumer subscribed to. Is it valid? How can we say which partition is assigned to the consumer using `subscribe` method? AFAIK if not specified a random partition is assigned.

**Comment by ppatierno** [comment]
Let's put the HTTP API interface out for a moment. As mentioned in the issue, the native Kafka consumer provides the `assignment` method for getting a list of `TopicPartition`.
We should check that it works even when you have used the `subscribe` method on the native client.
