### ISSUE TITLE
The operation to create consumer should not contain HTTP code 500 in response

### ISSUE THREAD

**Issue by serrss** [strimzi/strimzi-kafka-bridge#306]
Endpoint `POST ​/consumers​/{groupid}` returns HTTP status code 500 for some cases where we want to send a request with wrong data.
For example:
If sending a request to create consumer instance with a header `host=my-api-gateway-host;proto=mqtt` server returns `Internal Server Error` and `HTTP code 500`

My vision here, that we need to handle these cases and return a response with `HTTP code 400` and message what's wrong.

In the scope of this issue some ST should be also updated:
1. `ConsumerTest.createConsumerWithForwardedHeaderWrongProto`
2. `ConsumerTest.createConsumerWithWrongParameter`
3. `ConsumerTest.doNotReceiveMessageAfterUnsubscribe`

**Comment by serrss** [comment]
Related to #250

**Comment by ppatierno** [comment]
@serrss can you check if we can close it because the related #250 was already fixed.
