### ISSUE TITLE
Support OpenAPI in YAML format

### ISSUE THREAD

**Issue by serrss** [strimzi/strimzi-kafka-bridge#307]
If look at the OpenAPI Specification [1] we are able to see that default format of the `/openapi` endpoint is YAML. Right now ApenAPI in Kafka Bridge supports only JSON so so I expect that we need to add the support of YAML and make it as the default format. 

@ppatierno @stanlyDoge WDYT?

1. https://github.com/eclipse/microprofile-open-api/blob/1.x/spec/src/main/asciidoc/microprofile-openapi-spec.adoc#52-content-format

**Comment by ppatierno** [comment]
It's a Microprofile specification so I don't think it's an OpenAPI standard per se.
Anyway, we could provide YAML, even if we need to convert our JSON into it.

**Comment by scholzj** [comment]
This does not seem to be needed anymore and should be closed.
