### ISSUE TITLE
There is no validation for `format` during consumer creation

### ISSUE THREAD

**Issue by serrss** [strimzi/strimzi-kafka-bridge#309]
API returns `Internal Server Error HTTP 500` if try to create a consumer with wrong value for field `format`.
For example: 
```
{
  "name": "consumer1",
  "format": "foo", <------ we need validation here
  "auto.offset.reset": "earliest",
  "enable.auto.commit": "false",
  "fetch.min.bytes": "512",
  "consumer.request.timeout.ms": "30000"
}
```
Expected result:
HTTP code 4XX with message that Kafka Bridge supports onle binary and json formats

**Comment by ppatierno** [comment]
@serrss what's the current result? Do you have a log for that?

**Comment by ppatierno** [comment]
Ok I tested it and it just returns an internal server error 500.
We should return something like:

```json
{
    "error_code": 422,
    "message": "Invalid format type."
}
```
