### ISSUE TITLE
API returns status code HTTP 200 OK during sending records for a not existing partition

### ISSUE THREAD

**Issue by serrss** [strimzi/strimzi-kafka-bridge#312]
Kafka Bridge API returns HTTP code 200 OK for a request which has not existing partition Id in url.

**Step to reproduce:**
1. Deploy Kafka Bridge
2. Create a topic with the name "test" with one partition 
3. Send a POST request to the endpoint `/topics/{topicname}/topics/{topicname}/partitions/{partitionid}` where `topicname = test` and `partitionid = 1` with the following JSON:
```
{
  "records": [
    {
      "key": "key1",
      "value": "value1"
    }
  ]
}
```

Actual result: API returns HTTP code 200 with` "error_code": 404` and `"message": "Invalid partition given with record: 1 is not in the range [0...1)."`
Expected result: API shoud return status code 404 and corresponding message

**Comment by serrss** [comment]
After deep investigation this issue I figure out that this can error happen only if try to call endpoint `/topics/{topicname}` immediately after creating the topic, if wait 1-2 seconds, it's not possible to reproduce it. 
So, because of available to reproduce it only by automatic script, maybe we should close this issue? 
@ppatierno @stanlyDoge WDYT folks?

**Comment by ppatierno** [comment]
The discussion around the status code is part of the #311
