### ISSUE TITLE
Failed to deliver record when JSON body doesn't have partition

### ISSUE THREAD

**Issue by serrss** [strimzi/strimzi-kafka-bridge#316]
Delivering of record fails if try to use `POST /topics/{topicname}` endpoint without field "partition" in JSON

```
2019-09-03 14:59:37,149 [     vert.x-eventloop-thread-2] HttpSourceBridgeEndpoint       ERROR Failed to deliver record KafkaProducerRecord{topic=sendToOnePartitionTest,partition=null,timestamp=null,key=[B@4c1d6e4d,value=[B@2926efb4,headers=[]}
org.apache.kafka.common.errors.TimeoutException: Failed to update metadata after 60000 ms.
```

Step to reproduce:
1. Deploy Kafka Bridge
2. Create a topic with the name "test" with one partition
3. Send a POST request to the endpoint `/topics/{topicname}` where the record doesn't have `partition` field.
```
{
  "records": [
    {
      "key": "key1",
      "value": "value1"
    }
  ]
}
```
Actual result: if wait 60 secs, Kafka Bridge log has error `ERROR Failed to deliver record`
Expected result: No errors in logs. Record should be delivered.

**Comment by serrss** [comment]
After deep investigation this issue I figure out that this can error happen only if try to call endpoint /topics/{topicname} immediately after creating the topic, if wait 1-2 seconds, it's not possible to reproduce it.
So, because of available to reproduce it only by automatic script, maybe we should close this issue?
@ppatierno @stanlyDoge  WDYT folks?

**Comment by stanlyDoge** [comment]
Yes, I think we can close this.

**Comment by ppatierno** [comment]
The thing I see here is that, you say that waiting 1-2 seconds doesn't raise the issue but then from the log I see "Failed to update metadata after 60000 ms." so it seems that the producer is not able to fetch metadata about the created topic after 60 secs ... but if you wait 1-2 seconds it works. It sounds strange, isn't it?

**Comment by serrss** [comment]
@ppatierno thanks, good question. The script that I had, I executed in debug mode where I have breakpoints and moving between breakpoints takes 60+ seconds, this is why I had other error that you mentioned.

**Comment by ppatierno** [comment]
Ok, so we can close this.
