### ISSUE TITLE
It's possible to subscribe consumer to not existent topic

### ISSUE THREAD

**Issue by serrss** [strimzi/strimzi-kafka-bridge#320]
If try to send `POST` request to the endpoint `/consumers​/{groupid}​/instances​/{name}​/subscription` with non-existent topic name at JSON body, Kafka Bridge API will return a response with HTTP Status code 204 which means `Consumer subscribed successfully.`.

I guess Kafka Bridge Should handle this case and there is no topic to subscribe, API must return HTTP code 404 and error message that topic was not found.

Step to reproduce:
1. Start Kafka cluster
2. Deploy Kafka Bridge
3. Send POST request to the endpoint `/consumers​/{groupid}​/instances​/{name}​/subscription` where JSON body is:
```
{
  "topics": [
    "nonExistentTopicName" <----- non-existent topic name
  ]
}
```
Actual result: Response has HTTP status code 204
Expected result: Response must have HTTP status code 404 and error message

**Comment by ppatierno** [comment]
This is how the Kafka clients behave. Subscription doesn't really do the action of subscribing but the subsequent poll starts the operation of joining a consumer group and rebalancing partitions. Only in that moment, the Kafka client can handle a not existing topic.
