### ISSUE TITLE
Return subscribed topics in the case with using parameter `topic_pattern`

### ISSUE THREAD

**Issue by serrss** [strimzi/strimzi-kafka-bridge#321]
After using endpoint `POST /consumers/{groupid}/instances/{name}/subscription` I started to think that it will be great to know what's the topics you were subscribed when using `topic_pattern`. 

Because of using pattern can be is kind of tricky process and the admin can do some mistake and just to make sure that admin subscriber consumer to expected topics it will be really good to have subscriber topics in response to this endpoint.

**Comment by quickbooks2018** [comment]
https://www.youtube.com/watch?v=1Bv5SQW0BjI&t=336s&ab_channel=cloudgeeksinc

**Comment by ppatierno** [comment]
Going to close this, because in order to get this information there is now the possibility to use the `GET` method on the same endpoint. It will return the list of all topic/partitions subscription like the following.

```json
{
    "topics": [
        "my-topic"
    ],
    "partitions": [
        {
            "my-topic": [
                0
            ]
        }
    ]
}
```
