### ISSUE TITLE
Kafka Bridge logs output SCRAM-SHA-512 auth password in cleartext

### ISSUE THREAD

**Issue by jonganej** [strimzi/strimzi-kafka-bridge#343]
Upon starting up the Kafka Bridge pod, several configuration properties are output to logs, amongst others `kafka.sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="kafka-bridge-user" password="PASSWORD_IN_CLEAR_TEXT";`

The password component in `kafka.sasl.jaas.config` should be redacted or the property itself should not be shown to begin with due to security reasons.

**Comment by scholzj** [comment]
Which version were you trying it with? Also, could you share the log so that we can see where exactly this is happening? (feel free to mask the password of course ;-)) At least in one plase this should be now fixed in the startup scripts:

https://github.com/strimzi/strimzi-kafka-bridge/blob/85a17302e3ce4eca88a1562403ef9795fa602f89/bin/docker/kafka_bridge_run.sh#L24

That is part of the 0.14.0 release.

**Comment by jonganej** [comment]
Hi Jakub,

Sorry, I forgot to mention, I'm actually using AMQ Streams 1.2. I thought it might also be present in the upstream Strimzi project.

The log dump:
```
  | Preparing truststore
-- | --
  | Certificate was added to keystore
  | Preparing truststore is complete
  | Kafka Bridge configuration:
  | #Kafka common properties
  | kafka.bootstrap.servers=kafka-pilot-cluster-kafka-bootstrap:9093
  | kafka.security.protocol=SASL_SSL
  | #TLS/SSL
  | kafka.ssl.truststore.location=/tmp/strimzi/bridge.truststore.p12
  | kafka.ssl.truststore.password=PASSWORD_EXPOSED
  | kafka.ssl.truststore.type=PKCS12
  |  
  | kafka.sasl.mechanism=SCRAM-SHA-512
  | kafka.sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="kafka-bridge-user" password="PASSWORD_EXPOSED";
```
So it turned out to be the JAAS config as well as the `ssl.truststore.password` too.

**Comment by scholzj** [comment]
I do not think the `ssl.truststore.password` is really a secret TBH. It is randomly generated for the truststore created inside the container. It doesn't exist anywhere else. Teh `sasl.jaas.config` should be addressed in 0.14.0 release.

**Comment by jonganej** [comment]
Alright that's good to know. Thanks!

**Comment by ppatierno** [comment]
@scholzj I guess I can close this one right?

**Comment by scholzj** [comment]
Right. Sorry, I thought this was already closed.
