### ISSUE TITLE
Grafana Strimzi Integration

### ISSUE THREAD

**Issue by nishantkarve** [strimzi/strimzi-kafka-bridge#369]
_**This isn't an issue but a general request.**_ 

Are there any talks of integrating Strimzi with Grafana? This will allow the bridge administrators insights into the performance aspects of the bridge and identify bottlenecks if any. I am open to any other monitoring solution if it's already out there.

Thanks

**Comment by ppatierno** [comment]
Strimzi provide integration with Prometheus  for scraping the metrics and Grafana with related dashboards for showing them.
Actually they are metrics about Zookeeper, the Kafka brokers, and Kafka Connect plus some other metrics like consumers lag through Kafka Exporter. 
There are no metrics and related dashboard  about the bridge. Providing bridge metrics is in our backlog but there is no roadmap for that.

**Comment by nkarw** [comment]
Good to know. We are planning to use AWS SSM agents to monitor the EC2 instances where the bridge(s) will be set up.

**Comment by scholzj** [comment]
I think this is is a valuable issue. We should really have a metrics and dashboard for bridge as well. 

@ppatierno Do you think you can keep it in mind for the next planning session?

**Comment by ppatierno** [comment]
@stanlyDoge started to take a look into this because we have a pretty old issue (#72) about that (mostly on AMQP when the HTTP side wasn't in place). We decided to wait because it wasn't a higher priority for now.

**Comment by ppatierno** [comment]
The bridge is now supporting metrics exported via Prometheus.
There is also an example of Grafana dashboard in the Strimzi operator repository here: https://github.com/strimzi/strimzi-kafka-operator/blob/main/examples/metrics/grafana-dashboards/strimzi-kafka-bridge.json

Going to close this one as "implemented".
