### ISSUE TITLE
Error Code 406 - Different error than documented in Strimzi bridge documentation

### ISSUE THREAD

**Issue by nishantkarve** [strimzi/strimzi-kafka-bridge#373]
Hi,

I am testing a scenario where a malformed JSON is in a Kafka topic. I want to see how the bridge reacts to this malformed JSON. While reading the data from the kafka topic the bridge gave this error

`{"error_code":406,"message":"Failed to decode: Unexpected end-of-input: expected close marker for Object (start marker at [Source: (io.netty.buffer.ByteBufInputStream); line: 1, column: 1])\n at [Source: (io.netty.buffer.ByteBufInputStream); line: 1, column: 33]"}`

However, error code 406 in documentation states. 
`"message" : "The `format` used in the consumer creation request does not match the embedded format in the Accept header of this request."`

I rechecked that the format on the` /records` GET request is correct. While I understand that malformed messages can be handled upstream o the Kafka topic, what is expected out of the bridge if it does encounter a malformed JSON in the kafka topic. If I have 10 messages in the topic and the 5th one is malformed, the bridge ends up throwing an error all across without reading any single message. Is that expected?

The error codes could be misleading for the consumer.

**Comment by ppatierno** [comment]
@nkarw can you provide the malformed JSON you used?

**Comment by quickbooks2018** [comment]
https://www.youtube.com/watch?v=1Bv5SQW0BjI&t=336s&ab_channel=cloudgeeksinc

**Comment by ppatierno** [comment]
@nishantkarve after three years I am going to close this. Feel free to re-open if you can provide more info.
