### ISSUE TITLE
Ability to Enable CORS on Bridge

### ISSUE THREAD

**Issue by geoallenrh** [strimzi/strimzi-kafka-bridge#378]
Is there an option to enable CORS on the Kafka Bridge?    I’m trying to do a super simple Vue.js app to display some of the messages.  When the page is loaded, I receive the No 'Access-Control-Allow-Origin' header is present on the requested resource.

It looks like there are annotations on the standard Ingress for CORS, (nginx.ingress.kubernetes.io/enable-cors: "true”, etc), but wondering if there is something similar for the Kafka Bridge and if that would resolve the issue.

**Comment by ppatierno** [comment]
There is no such a support for this right now but thanks for raising this point. I will take a look at it.

**Comment by hifly81** [comment]
From a tech point of view all you need is in 
import io.vertx.ext.web.handler.CorsHandler 

I think the best is enabling (on/off) with a bridge property (e.g cors.enabled=true|false)
