### ISSUE TITLE
make java_package doesn't work for clean install

### ISSUE THREAD

**Issue by morgangalpin** [strimzi/strimzi-kafka-bridge#388]
To reproduce:
`make clean java_package`

The unit tests run and fail on `StaticTests.bridgeVersionDisplayedInStartupTest()`.

This is because the test phase relies on an artifact of the `maven-assembly-plugin:...:single` which runs after the `test` phase of maven.

To get the build to work, I needed to run:
```
MVN_ARGS=-DskipTests make clean java_package
make java_package
```

This is not ideal, as it takes longer, and the bridge version test isn't testing the current code, but an artifact of a previous build.

**Comment by ppatierno** [comment]
Yeah we are aware of that. @granzoto you should try to think about a different test for that.
