### ISSUE TITLE
Strimzi specific metrics not exposed with JMX.

### ISSUE THREAD

**Issue by samik1996** [strimzi/strimzi-kafka-bridge#391]
I'm enabling JMX port for Strimzi -Kafka bridge by adding these lines in the Kafka-Bridge.sh file.

-Dcom.sun.management.jmxremote.port=9250
-Dcom.sun.management.jmxrempte.rmi.port=9250
-Dcom.sun.management.jmxremote.authenticate=false
-Dcom.sun.management.jmxremote.ssl=false

After this, when I run strimzi and check it in JConsole for the available Metrics, I only get to see basic Java metrics. But no Strimzi specific metrics are available.

Is there a way to enable strimzi specific Metrics? Is there any more configuration required? Am I missing something?

<img width="680" alt="Screenshot 2020-03-06 at 5 08 16 PM" src="https://user-images.githubusercontent.com/48542758/76096227-beb97580-5feb-11ea-80ca-0660d502cc97.png">

**Comment by scholzj** [comment]
I do not think the Bridge provides any specific metrics at this point. And the future plans would probably add them as Prometheus metrics rather than JMX.

**Comment by samik1996** [comment]
I am looking for Kafka Lag. Does it provide Kafka Lag metric?

**Comment by scholzj** [comment]
The Kafka Exporter provides lag metrics: https://strimzi.io/docs/latest/full.html#assembly-kafka-exporter-configuration-deployment-configuration-kafka

**Comment by ppatierno** [comment]
As today, the bridge provides metrics via Prometheus related to producer and consumer but not lag and as Jakub mentioned it's provided by Kafka Exporter. Because this issue is stale I am going to close this. @samik1996 feel free to re-open if needed.
