### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by kozelok** [strimzi/strimzi-kafka-bridge#400]
What kind of performance can I expect from this in the following config:
10-20 HTTP Publishers
8KB payloads
Connect Keep Alive

Thank you and stay safe!

**Comment by ppatierno** [comment]
You could try to run a performance test for this. We are providing a JMeter configuration under the `perftest` folder that could be tuned for getting the information you need.

**Comment by quickbooks2018** [comment]
https://www.youtube.com/watch?v=1Bv5SQW0BjI&t=336s&ab_channel=cloudgeeksinc
