### ISSUE TITLE
Assignment to non-existing partition does return 204

### ISSUE THREAD

**Issue by sknot-rh** [strimzi/strimzi-kafka-bridge#491]
If we have a topic with 3 partitions and try to assign partition >2, we got a warn in the bridge console, but the bridge returns `204`.We should discuss whether it is correct or we should return different status code.

**Comment by ppatierno** [comment]
This is how the underlying native Java Kafka client works. It will be assigned and start receiving messages as soon as the topic/partitions are created. It was also addressed in this PR https://github.com/strimzi/strimzi-kafka-bridge/pull/708
