### ISSUE TITLE
Enable AMQP in Kubernetes

### ISSUE THREAD

**Issue by Vetm** [strimzi/strimzi-kafka-bridge#511]
Is it possible to run the kafka-bridge with AMQP in Kubernetes? The [helm chart](https://github.com/strimzi/strimzi-kafka-operator/blob/main/helm-charts/helm3/strimzi-kafka-operator/crds/046-Crd-kafkabridge.yaml) doesn't seem to expose the [config variables](https://github.com/strimzi/strimzi-kafka-bridge/blob/main/config/application.properties#L16) for it.

Also, the readme says:
> You can use the Strimzi Kafka operator to deploy the Kafka Bridge **with HTTP support** on Kubernetes and OpenShift.

Does this mean I can't enable AMQP in Kubernetes? If so, why is this the case?

**Comment by scholzj** [comment]
The deployment through the operator does not support AMQP right now. That is mainly the limitation of the operator. There is no reason why you would not be able to use it on Kubernetes, you just need to deploy it manually.

**Comment by ppatierno** [comment]
Closing this one because the bridge doesn't support AMQP 1.0 protocol anymore.
