### ISSUE TITLE
Deserialisation in RabbitMq for generic class 

### ISSUE THREAD

**Issue by ankisinha3005** [strimzi/strimzi-kafka-bridge#531]
I have a generic class RetryEnquiry , i'm trying to consume it in Consumer class . I have specified the Car class in Rabbit handler , still the jackson deserialiser is unable to understand that and converts it to ListHashMap. Can anyone please help me in converting it to Car class.

<img width="726" alt="Screenshot 2021-06-29 at 2 49 27 AM" src="https://user-images.githubusercontent.com/32894171/123705506-acb8b180-d884-11eb-87ea-b950f1cadb88.png">
<img width="691" alt="Screenshot 2021-06-29 at 2 49 15 AM" src="https://user-images.githubusercontent.com/32894171/123705528-b510ec80-d884-11eb-8046-67938e310012.png">

**Comment by scholzj** [comment]
Sorry, how does this relate to Strimzi Kafka Bridge?

**Comment by ankisinha3005** [comment]
Extremely Sorry @scholzj  , i am new to this platform  .
