### ISSUE TITLE
Additional quotes are added to a message

### ISSUE THREAD

**Issue by alesj** [strimzi/strimzi-kafka-bridge#539]
To reproduce
* run Kafka
* run console consumer
* run Bridge
* post message to the Bridge via curl

```
curl -X POST \
  http://localhost:8080/topics/mytopic \ 
  -H 'content-type: application/vnd.kafka.json.v2+json' \
  -d '{
  "records": [
    {
      "value": "value"
    }
  ]
}'
```

In the console consumer you should see extra quotes

```
kafka_2.13-2.8.0 % ./bin/kafka-console-consumer.sh --topic mytopic --bootstrap-server localhost:9092

"value"
```

**Comment by scholzj** [comment]
Thsi was already discussed in #461

**Comment by aholmberg** [comment]
I think this is a real issue. I believe the Json encoding [here](https://github.com/strimzi/strimzi-kafka-bridge/blob/0c0426832f783a82cfe6e75cd86f867f8e8fdec6/src/main/java/io/strimzi/kafka/bridge/http/converter/HttpJsonMessageConverter.java#L40) is taking the base64 encoded value and putting additional quotes around it. So what goes on topic is `json(base64(data))`.
The binary converter, on the other hand, actually appears to [decode](https://github.com/strimzi/strimzi-kafka-bridge/blob/0c0426832f783a82cfe6e75cd86f867f8e8fdec6/src/main/java/io/strimzi/kafka/bridge/http/converter/HttpBinaryMessageConverter.java#L40) the base64 body, so I think just `data` goes on topic.

**Comment by ppatierno** [comment]
Closing as duplicate.
