### ISSUE TITLE
Problem with latency

### ISSUE THREAD

**Issue by Arfey** [strimzi/strimzi-kafka-bridge#540]
Hi ✋

The vast majority of kafka bridge requests have good response times (less than 200ms), but some have more than 2-5 seconds. I tried to find the problem and check the latency from the pod for the `/ready` handler (to rule out kafka and networking issues), but also some requests had response times more than 1-2 seconds.

Without a load, this problem is not present (produce 2-3 messages per second).

```
repository: strimzi/kafka-bridge
tag: "0.19.0"
jvmOptions: -Xmx512m -Xms512m
```

i guess i have not problem with gc or heap (even when i increase the memory it does not give any result).  Also i have not problem with cpu:

```
cpu usage: ~1%
memory: ~400mb
```

i have discover problem (1-3%) with throttling and increase count of cores for bridge from 1 to 4 (throttling 0%) and it have decreased some count of slow requests but not fully solved my problem

Someone knows what might be wrong or how i can solve a current problem? Thx!

**Comment by scholzj** [comment]
@sknot-rh @ppatierno Any ideas?

**Comment by Torbik** [comment]
I'd like to add a few additions to this case:
- the bridge is used as a producer
- thread count was increased over time:
![image](https://user-images.githubusercontent.com/970979/133658133-4b3c9635-212e-449a-a09e-36cf52d66295.png)

I suspect so many threads give significant overhead that affects overall performance.

**Comment by sknot-rh** [comment]
Hi. Are you sure you do use bridge just as a producer? I did some testing and when the bridge is just producing records, it won't get over 54 threads.

**Comment by Arfey** [comment]
Sure. Current instance use only for producing messages

**Comment by ppatierno** [comment]
@Arfey I am going to close this issue, not hearing from you since years. Feel free to re-open if the problem seems to be still in place for you.
