### ISSUE TITLE
Bumping the Kafka version to 2.8.1 since 3.0.0 causes failure

### ISSUE THREAD

**Issue by ShubhamRwt** [strimzi/strimzi-kafka-bridge#544]
The Bridge currently support the max kafka version of 2.8.1. Bumping the kafka version to 3.0.0 cause test failures since many changes were introduced in kafka 3.0.0 which is not compatible with Vert.x.

Error :-
2021-10-01T09:02:15.4463298Z java.lang.NoSuchMethodError: 'long org.apache.kafka.clients.producer.RecordMetadata.checksum()

**Comment by sknot-rh** [comment]
FYI I've opened the PR to bump up the Kafka version in vertx client to 3.0.0 but it won't be merged any soon as the debezium dependency (used for tests) still uses Kafka 2.8.0. https://github.com/vert-x3/vertx-kafka-client/pull/208

**Comment by ShubhamRwt** [comment]
@scholzj @sknot-rh Are we planning to use vert.x Kafka for the new releases or do we intend to remove it and use an alternative which supports Kafka 3.0?

**Comment by sknot-rh** [comment]
Kafka 3.0.0 support is planned in Vertx 4.3. 
From a long-term POV it would be good to remove vertx-kafka-client dependency.

**Comment by ppatierno** [comment]
Going to close this because it isn't an issue anymore.
