### ISSUE TITLE
Can we create custom endpoint url for kafka rest proxy?

### ISSUE THREAD

**Issue by raje143r** [strimzi/strimzi-kafka-bridge#560]
Hi, 
I'm trying to add my own endpoint url to expose my kafka rest proxy but seems it's not allowed. 
As when call curl get method to get topics list, getting "Http 404 not found error" .
could you please suggest where and how can declare our custom rest endpoint for kafka bridge.

for ex: http:<<IPAddress>>:<<Port>/testurl/testchkpoint

Thanks in advance.

**Comment by scholzj** [comment]
Maybe you should explain what do you mean with _custom endpoint URL_.

**Comment by raje143r** [comment]
Hi Jakub,
currently Kafka rest API looks like http://<<IPAddress>>:<<Port>>(ex: http://localhost:8082).. So if we want to get topics list, we have to use http://<<IPAddress>>:<<Port>>/topics.  
Now my endpoint url  should be with url i.e http://<<IPAddress>>:<<Port>>/testurl/testchkpoint . 
so my rest client will use http://localhost:8082/testurl/testchkpoint/topics to get list of topics. 

Thanks in advance

**Comment by scholzj** [comment]
I'm still not sure I follow completely why would you do that. I don't think the bridge supports it -> but you should be able to just use some proxy which will rewrite the address from your format to the bridge format.

**Comment by raje143r** [comment]
Hi Jakub,

you mean, we can't create our custom kafka bridge rest endpoint url like http://localhost:8082/testurl/testchkpoint/topics

Thanks in advance

**Comment by scholzj** [comment]
Well, as I said - as far as I know the bridge it self does not allow it (I also don't understand how/why it would be useful). But you can do it in some proxy or API Gateway and just redirect the requests to the right Bridge URL.

**Comment by ppatierno** [comment]
@raje143r is the answer from Jakub enough? Can we close this one or do you still have any doubt? Bridge doesn't support what you are asking for but you would need a proxy in front of it.

**Comment by ppatierno** [comment]
@raje143r I am going to close this, feel free to re-open if you need more information.
