### ISSUE TITLE
SchemaRegistry entry in kafkabridge yaml

### ISSUE THREAD

**Issue by raje143r** [strimzi/strimzi-kafka-bridge#567]
Hi,
Could you please share how to enter schema registry endpoint in the kafkabridge.yml in stirmzi. So that I will send data to topic with AVRO format. 
I found the below format , but seems not working. 
schema.registry.url=http://localhost:8081 

Thanks in advance.

**Comment by scholzj** [comment]
The KafkaBridge CR has fields for setting the consumer and producer configuration. But I don§t think it supports any Schema registry.

**Comment by raje143r** [comment]
Thanks jakub. it will be helpful if you can share kafkaBridge CR details.

**Comment by scholzj** [comment]
I do not have the links at hand. But in the doc - in the Using guide, you should find all the details.

**Comment by raje143r** [comment]
Ok

**Comment by raje143r** [comment]
Hi Jakub,

I have tried to find  details for KafkaBridge CR. I found  below information. But my schema registry setup has done by using strimzi script. So if i use different api platform(platfrom.confluent.io) then will be a problem. It will be helpful if you have any suggestion to enable schema registry from KafkaBridge.yml

apiVersion: platform.confluent.io/v1beta1
kind: KafkaRestProxy
metadata:
  name: kafkarestproxy
  namespace: operator
spec:
  authentication:
    basic:
      secretRef: kafkarestproxy-users
    type: basic
  dependencies:
    schemaRegistry:
      authentication:
        basic:
          secretRef: sr-client-basic
        type: basic
      tls:
        enabled: true
      url: https://schemaregistry.operator.svc.cluster.local:8081
  image:
    application: confluentinc/cp-kafka-rest:7.0.0
    init: confluentinc/confluent-init-container:2.2.0
    pullSecretRef:
      - confluent-registry
  replicas: 3
  tls:
    autoGeneratedCerts: true

Thanks in advance

**Comment by scholzj** [comment]
Well, as I said in the beginning, I don't think we support any registry in the bridge. The bridge will nto do any validation or conversion. I never used the Confluent Schema Registry, but I'm not sure whatever you are looking for is possible.

**Comment by raje143r** [comment]
Thankyou Jakub
