### ISSUE TITLE
Enable to read only commited transactional messages for exactly-once guarantee in KafkaConsumer

### ISSUE THREAD

**Issue by sonic-martin** [strimzi/strimzi-kafka-bridge#577]
The [KafkaConsumer API](https://strimzi.io/docs/operators/latest/using.html#controlling_transactional_messages) allows to read only commited transactional messages for allow exactly-once guarantee inKafkaConsumer via setting ```isolation.level=read_committed``` on consumer-side.

This setting is not possible to setup via Kafka Bridge.
It would nice to be able to set it up via [Consumer-Creation](https://strimzi.io/docs/bridge/latest/#_consumer).

Howerever, its possible to set it up for all consumers via [Kafka Bridge configuration in the Strimzi operator](https://strimzi.io/docs/operators/latest/using.html#assembly-config-kafka-bridge-str).

**Comment by ShubhamRwt** [comment]
Closing this issue , since it is resolved in #585
