### ISSUE TITLE
[QUESTION] Motivations to build kafka-bridge ?

### ISSUE THREAD

**Issue by raphaelauv** [strimzi/strimzi-kafka-bridge#586]
Hello I'm trying to understand what are the motivations to build this project, and the difference with

the confluent rest-proxy project -> https://github.com/confluentinc/kafka-rest

and the redpanda rest proxy -> https://github.com/vectorizedio/redpanda/discussions/1295

Thank you

**Comment by scholzj** [comment]
Strimzi Kafka Bridge is our component for integrating between Kafka and other protocols. It is integrated with the Strimzi Cluster Operator and has an open source license.

**Comment by raphaelauv** [comment]
Thanks for your answer
