### ISSUE TITLE
Discussion on AMQP partition annotation

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi-kafka-bridge#6]
Let's discuss if current implementation is good on using AMQP message annotation for specifying partition on sender side or it could be better to have this info inside the address.

Current implementation use "x-opt-bridge.partition" as message annotation.
Could it be better to use something like "my_topic/partitions/[partition_id]" ?

The first (current) implementation seems to be simpler to handle on bridge side (quick access to annotations inside the message) but annotations aren't so much used on client side ? The second one is more friendly to the sender client (thinking in terms of URI) but "more complex" for bridge related to the address parsing needed.

**Comment by grs** [comment]
Either sounds good to begin with. The other approach can always be added in as an alternative option later.

**Comment by ppatierno** [comment]
Closing this one because the bridge doesn't support AMQP 1.0 protocol anymore.
