### ISSUE TITLE
Multiple Verticles

### ISSUE THREAD

**Issue by tombentley** [strimzi/strimzi-kafka-bridge#62]
Currently the bridge consists of one Vert-X `Verticle` (the `Bridge` itself). This means that there's just one thread running all the code for both source and sink, across all the endpoints. At some scale that will become a bottleneck. Within openshift we can just scale up by using more pods, but it's wasteful to require more pods to tackle something which could be (easily?) tackled at the application layer.

To use more threads for the processing of messages we basically have to have more verticles in the application, and the obvious candidates for those are the endpoints.

The prerequisite for that refactoring is finding the current scaling limit is indeed a problem.

**Comment by scholzj** [comment]
As we are slowly moving away from Vert.x, I think this is not relevant anymore.
