### ISSUE TITLE
Processing rest of batch on closing endpoint

### ISSUE THREAD

**Issue by tombentley** [strimzi/strimzi-kafka-bridge#65]
When we close the endpoint should we try to finish processing the rest of the batch of messages that's already been fetched from Kafka or just close immediately? 

In `AT_MOST_ONCE` QoS, if we just close immediately then those messages are lost. That is, of course, allowed, but it's not losing them if we don't have to would be better.

Likewise in `AT_LEAST_ONCE` we will end up redelivering messages next time we start. But this case would be harder to do something about because we would have to process the messages remaining in the batch and then wait for their dispositions.

**Comment by ppatierno** [comment]
Closing this one because was referring to AMQP 1.0 support which was removed.
