### ISSUE TITLE
Tracing failed `poll` operation on HTTP consume request

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi-kafka-bridge#653]
Currently, the tracing span for a `poll` operation is created only when the actual Kafka poll ends successfully:
This happens in the `HttpSInkBridgeEndpoint.pollHandler` method here:

https://github.com/strimzi/strimzi-kafka-bridge/blob/main/src/main/java/io/strimzi/kafka/bridge/http/HttpSinkBridgeEndpoint.java#L249

Kafka poll success means `records.succeeded()` is true.
It means that there is no way to trace a failed Kafka poll, while OpenTelemetry allows to set an ERROR status on a span.
I think we should move the `poll` span creation earlier to be used even when the Kafka poll operation fails.

**Comment by ShubhamRwt** [comment]
Closing this since #655 is now merged
