### ISSUE TITLE
Metrics and monitoring

### ISSUE THREAD

**Issue by tombentley** [strimzi/strimzi-kafka-bridge#72]
We currently lack any kind of monitoring or metrics in the bridge. It would be useful to know things like:

* The address of the currently connected AMQP links and Kafka topics with details (e.g. QoS, partition and current offset for Kafka consumers)
* The message processing rate (overall and per topic)
* A response time histogram
* Histogram for time spent in user code (or what could be user code, for example message conversion)
* The number of dropped/unprocessable messages (depending on the resolution of #66)

Some of these may already be available from Proton/Kafka in which case we just need test to ensure they're available.

**Comment by pushpithaDilhan** [comment]
I would like to work on this.
