### ISSUE TITLE
OOM of Kafka bridge container due to cgroupv2 (Debian11, Ubuntu 21+...)

### ISSUE THREAD

**Issue by soltiz** [strimzi/strimzi-kafka-bridge#731]
By default, new distributions of linux use cgroupv2
Strimzi uses /sys/fs/cgroup/memory.limit_in_bytes in dyamic_resources.sh, but this stat does not exist in cgroupv2.
Therefore the script returns nothing, and the JVM uses default memory setting.
When JVM Heap exceeds configured pod limit, pod is killed.

Solution: Detect if cgroup is v2 (e.g. memory.limit_in_bytes does not exist), and use instead memory.max which is in cgroupv2.

The same bug applies also to Zookeeper and Kafka Pods launched by Strimzi operator, but is maybe present also in operator pods.

**Comment by scholzj** [comment]
Thanks for raising this. It indeed seems to be issue for the Bridge. However, the Strimzi operators and its images calculate the memory differently. So I do not think it is a problem there (unless you use some old version, in which case you should upgrade).
