### ISSUE TITLE
Principal Propagation for Kafka Bridge Auth Client and Kafka Broker

### ISSUE THREAD

**Issue by sookeke** [strimzi/strimzi-kafka-bridge#738]
Hello - 

We currently have a use case where we already secured the Kafka bridge via a revere-proxy OAuth2-proxy. Now, we want Kafka bridge to use the same client credentials/token/auth-header from the reverse proxy OAuth2-proxy when making a request to the Kafka broker with authorization enabled. This will allow Kafka bridge clients via OAuth2-proxy to only consume or produce to topics they are permitted to from the ACL.

propose solution may be to take the principal from the authentication mechanism from the Kafka bridge Oauth2-proxy client and propagate that same principle when making a request to the Kafka broker with authorization enabled.

**Comment by scholzj** [comment]
You cannot just _propagate a principal_. You would need to authenticate the connection for the given client. So I think this is way more complicated than it sounds.

**Comment by sookeke** [comment]
What could be the possible workaround for this use case if there's any?

**Comment by scholzj** [comment]
I'm not sure what exactly you want to work around. The bridge currently does not support any kind of identity propagation or passthrough authentication.

**Comment by sookeke** [comment]
I figured. I was thinking there might be some thought toward a more secure use of the bridge. Thanks for the response

**Comment by scholzj** [comment]
It is something that we would love to support one day. But it is not completely trivial to separate the client sessions, pass through the credentials etc. So I do not think we will get to it anytime soon. But of course - contributors are always welcomed.
