### ISSUE TITLE
Add a new `string` embedded format

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi-kafka-bridge#739]
Currently, we have the `binary` and `json` embedded format.
The JSON one is used for handling messages key and message as JSON, while the binary one allows to set them a Base64 encoded String from corresponding binary data.
As per #410, users need to transfer key and value which are simple raw strings and not JSON strings, so without quotes.
This is not possible with the `json` embedded format because it's not simple detect that a key or value is a simple String or just a malformed JSON (see #737 for more details).
Using the `binary` mode to transfer simple strings works but it's an hack.

In order to allow the simple strings use case, we could add a new `string` embedded format in the bridge.

**Comment by ShubhamRwt** [comment]
One thing what you can do for testing things without docker is that you can run the bridge in the DEBUG mode in your editor . You can set up breakpoints in the code at places which will be triggered when you are testing your functionality(for eg, the method you changed, the method or code which is calling the method you changed etc.). Then you can go onto the `Application.java` class and run it in the debug mode. Note: You will have to run/debug `Application.java` class by providing it the config file like this `--config-file config/application.properties`. If you are using Intellij you can easily do this by editing the run/debug configuration.

**Comment by antonio-pedro99** [comment]
@ppatierno if I understood, the bridge should support `text/plain` and `application/vnd.kafka.text.v1+json`, is that correct?
cc: @scholzj

**Comment by antonio-pedro99** [comment]
> @ppatierno if I understood, the bridge should support `text/plain` and `application/vnd.kafka.text.v1+json`, is that correct? cc: @scholzj

reminder

**Comment by scholzj** [comment]
I think the request sent to the Bridge will be always JSON. But inside the JSON as the body of the Kafka message, you would have just a String and not JSON. I'm not sure if @ppatierno had any more thoughts about how can it be implemented.

**Comment by ppatierno** [comment]
To add more to the already good answer from Jakub, let me say that the bridge has a payload and embedded format.
The payload is always JSON but the embedded format can be different.
Right now the two embedded format are `json` or `binary`. It helps the bridge to understand that inside the payload, values are in JSON or are binary (base64 encoded).
What you should have is a new embedded `string` format.
Take a look at the `BridgeContentType` class here: https://github.com/strimzi/strimzi-kafka-bridge/blob/main/src/main/java/io/strimzi/kafka/bridge/BridgeContentType.java#L11
I would envisage a new `"application/vnd.kafka.string.v2+json"` type and corresponding handling by the bridge.
Just as a side note, we could even call it `text` and not `string` embedded format. Maybe `text` is more generic.
