### ISSUE TITLE
CrashLoopBackoff due to no /tmp/strimzi cleanup at start (when OOM causes failures)

### ISSUE THREAD

**Issue by soltiz** [strimzi/strimzi-kafka-bridge#753]
When for any reason the kafka bridge pod is killed (e.g. Memory exhaust causing OOM Killer ), the vertx cache create new folders in /tmp/strimzi, in turn leading to a "no space left on device" at startup.

A "rm -rf /tmp/strimzi" could be done before "mkdir /tm/strimzi" in the startup script ?

**Comment by scholzj** [comment]
It should, yes. Similarly to what we do in the operators for example: https://github.com/strimzi/strimzi-kafka-operator/blob/main/cluster-operator/scripts/cluster_operator_run.sh#L4-L6

**Comment by ppatierno** [comment]
Yes, good catch! @soltiz maybe you could open a PR and contribute? Otherwise I will do.

**Comment by ppatierno** [comment]
@soltiz are you still interested in working on this one? Otherwise, I have got @im-konge asking for it. Let us know, please.
