### ISSUE TITLE
Make run script less Kubernetes/OpenShift aware

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi-kafka-bridge#76]
The run_bridge.sh script is used today for launching the AMQP - Kafka bridge but it seems to me too much strictly related to EnMasse.
I see that such script sets the `AMQP_MODE`, `AMQP_HOST` and `AMQP_PORT` env vars with `CLIENT` mode and host/port related to Kubernets/OpenShift EnMasse services using the conventional naming (i.e. $MESSAGING_SERVICE_XXXXX).
As @scholzj has already provided the `AMQP_CERT_DIR` env dir EnMasseProject/enmasse#199 it should be done even for the above env vars.
Today the EnMasse configuration sets the `KAFKA_BOOTSTRAP_SERVERS` as well and the script just does a check to be sure on that and then usew the $KAFKA_SERVICE_XXXX env vars if it's not set.
I'm not sure that it should be done. Maybe the script should just launch the bridge while all env vars set should be done at EnMasse (container) configuration level.
Wdyt @lulf @scholzj @tombentley ?

**Comment by scholzj** [comment]
I agree. The Docker image should be IMHO usable on its own in both modes and it should be configurable from the outside.

+1 to moving the configuration into the Kubernetes / Openshift deployment and keeping the run_bridge.sh as generic as possible.
