### ISSUE TITLE
Use appropriate class for the KafkaBridgeProducer logger

### ISSUE THREAD

**Issue by antonio-pedro99** [strimzi/strimzi-kafka-bridge#813]
Was it intentional using the KafkaBridgeConsumer to create a logger for the KafkaBridgeProducer?

For your reference: https://github.com/strimzi/strimzi-kafka-bridge/blob/eab72b43d3b63742a2ffa3da2891235ab310564c/src/main/java/io/strimzi/kafka/bridge/KafkaBridgeProducer.java#L28

**Comment by ppatierno** [comment]
Good catch! I have just opened PR #814  for it, Thanks!
