### ISSUE TITLE
English typo

### ISSUE THREAD

**Issue by antonio-pedro99** [strimzi/strimzi-kafka-bridge#825]
https://github.com/strimzi/strimzi-kafka-bridge/blob/5d532de182c89c3b05722a37efc17df00d246d98/src/test/java/io/strimzi/kafka/bridge/http/base/HttpBridgeITAbstract.java#L149

**Comment by ppatierno** [comment]
@antonio-pedro99 I think you fixed this in your own repo but never opened a PR against the main one. Are you going to do that?

**Comment by antonio-pedro99** [comment]
> @antonio-pedro99 I think you fixed this in your own repo but never opened a PR against the main one. Are you going to do that?

Yes, you are right :) I thought you have merged it before.
