### ISSUE TITLE
`No schema matches` error raised when key or value in a `json` record is a JSON array

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi-kafka-bridge#892]
When using the `json` embedded format and sending a message like the following ...

```json
{
  "records": [
    {
      "value": "my-value",
      "key": ["element1",{"field": "element2"}]
    }
  ]
}
```

The bridge returns ...

```json
{
    "error_code": 400,
    "message": "Validation error on: /records/0/key - No schema matches"
}
```

This error is raised by the internal Vert.x JSON schema component which is doing the validation on the `key` field based on the definition we have in the OpenAPI ...

```json
"key": {
    "oneOf": [
        {
            "type": "object"
        },
        {
            "type": "string"
        }
    ]
}
```

It should work because it's defined as a JSON object, and the array in the example is a valid JSON object.
So it seems that the array is making troubles to the validator.
The same happens if using the same to the `value` field of course.

**Comment by ppatierno** [comment]
Taking a look at this, the issue seems to be on our OpenAPI definition.
The `key` (and  `value`) for the records should be defined also as `array` as possible type. So something like:

```json
"key": {
    "oneOf": [
        {
            "type": "array"
        },
        {
            "type": "object"
        },
        {
            "type": "string"
        }
    ]
}
```

Because of course OpenAPI spec uses the JSON Schema Definition where "array" is used as type for a JSON array (an array with JSON object insides).

**Comment by antonio-pedro99** [comment]
Hi @ppatierno, I have done something for this, late I will raise the PR
