### ISSUE TITLE
Move travis scripts from EnMasseProject to Strimzi. 

### ISSUE THREAD

**Issue by shubhamvashisht** [strimzi/strimzi-kafka-bridge#90]
the travis.yml file is still using test and build scripts from EnMasseProject as mentioned in #84 . Should we move these scripts under strimzi itself?

**Comment by scholzj** [comment]
I'm not sure they should be moved one to one. MAybe we can keep only the features which are needed. WDYT @ppatierno ?

**Comment by shubhamvashisht** [comment]
@ppatierno Any suggestions on this?

**Comment by ppatierno** [comment]
I am going to close this one because we have to review the Travis CI without any relationship with EnMasse.
