### ISSUE TITLE
get message publish timestamp

### ISSUE THREAD

**Issue by hsiaand** [strimzi/strimzi-kafka-bridge#912]
Hi

I am looking to get message publish timestamp on the returned json payload from consumer subscription.
Any option or ways to get this info?

**Comment by ppatierno** [comment]
It's not possible right now. As you can see it's not in the `ConsumerRecord` OpenAPI definition here https://github.com/strimzi/strimzi-kafka-bridge/blob/main/src/main/resources/openapi.json#L1512
It's also missing on the producer side https://github.com/strimzi/strimzi-kafka-bridge/blob/main/src/main/resources/openapi.json#L1838

**Comment by ppatierno** [comment]
Triaged on 13/6/2024: it makes sense to have this implemented to reflect what users already have when using the Kafka consumer/producer API.

**Comment by antonio-pedro99** [comment]
@ppatierno I will be working on this.

**Comment by ppatierno** [comment]
Cool, thanks @antonio-pedro99

**Comment by ppatierno** [comment]
> Should we care about the ProducerRecord's timestamp too?

Yes. We should provide the same UX we have with the Kafka Producer API which, as you can see here https://javadoc.io/doc/org.apache.kafka/kafka-clients/latest/org/apache/kafka/clients/producer/ProducerRecord.html, allows to specify the timestamp on the produced record.

**Comment by antonio-pedro99** [comment]
> > Should we care about the ProducerRecord's timestamp too?
> 
> Yes. We should provide the same UX we have with the Kafka Producer API which, as you can see here https://javadoc.io/doc/org.apache.kafka/kafka-clients/latest/org/apache/kafka/clients/producer/ProducerRecord.html, allows to specify the timestamp on the produced record.

I got it. My question is, should the users mention the timestamp while producing messages? This is something the bridge can handle it internally.

**Comment by ppatierno** [comment]
As I said, we should provide same UX experience as a Kafka Producer API, where the user provides the timestamp.
The same has to be supported when using the HTTP client. Of course, the timestamp isn't mandatory (as for the Kafka Producer API).
